stages:
  - lint
  - test
  - build

before_script:
  - rustc --version
  - cargo --version

variables:
  RUSTFLAGS: -D warnings

lint:fmt:
  stage: lint
  image: 'rustlang/rust:nightly'
  allow_failure: true
  script:
    - cargo fmt -- --check

lint:clippy:
  stage: lint
  image: 'rust:latest'
  allow_failure: true
  before_script:
    - rustc --version
    - cargo --version
    - rustup component add clippy
  script:
    - cargo clippy -- -D warnings

test:stable:
  stage: test
  image: 'rust:latest'
  script:
    - cargo test

test:nightly:
  stage: test
  image: 'rustlang/rust:nightly'
  script:
    - cargo test

build:stable:release:
  stage: build
  image: 'rust:latest'
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/wag_archive_util

build:stable:debug:
  stage: build
  image: 'rust:latest'
  script:
    - cargo build

build:nightly:release:
  stage: build
  image: 'rustlang/rust:nightly'
  allow_failure: true
  script:
    - cargo build --release

build:nightly:debug:
  stage: build
  image: 'rustlang/rust:nightly'
  allow_failure: true
  script:
    - cargo build
